version: '3.8'

services:

  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8888:8888"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

